# Generated by Django 4.0.1 on 2022-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Open', models.FloatField(max_length=20)),
                ('High', models.FloatField(max_length=20)),
                ('Low', models.FloatField(max_length=20)),
                ('Close', models.FloatField(max_length=20)),
                ('Adjusted_Close', models.FloatField(max_length=20)),
                ('Volume', models.IntegerField()),
            ],
        ),
    ]
